title: "Musa Rangrez"
logo: "/assets/roundedheadshot.png"
theme: "jekyll-theme-minimal"

# Technical Skills
technical_skills:
  - Python
  - SQL
  - MATLAB
  - AWS
  - Tableau

# Education
education:
  - "**B.S., Computer Science**, Oregon State University (Expected May 2025)"
  - "**B.A., Public Health Policy**, University of California, Irvine (June 2022)"

# Work Experience
work_experience:
  - "**Data Analyst Intern**, 1800 Hiring (Jan 2023 – Jun 2024):  
    Leveraged data-driven insights to enhance recruitment efficiency, achieving a 15% reduction in time-to-fill and a 20% improvement in candidate-to-job matches. Specialized in performance reporting, data cleaning, and process optimization."

  - "**Undergraduate Research Assistant**, UCI Health (Jun 2021 – Mar 2022):  
    Conducted research on orthotropic appliance prototypes using MATLAB and machine learning to predict orthodontic corrections with 91.3% accuracy. Designed a Python/MATLAB interface to analyze clinical trial data, track algorithm performance, and optimize case planning for over 50 trials."

# Projects
projects:
  - "**[NFL Big Data Bowl Competition 2025](https://github.com/kashmir98/NFL-Big-Data-Bowl-2025)**:  
    Leveraged player tracking data to predict pre-snap to post-snap dynamics, utilizing Python and machine learning to generate actionable insights into team strategies and player behavior."

# Contact Me
contact_me:
  - "**Email**: [musarangrez@hotmail.com](mailto:musarangrez@hotmail.com)"
  - "**LinkedIn**: [linkedin.com/in/musarangrez](https://linkedin.com/in/musarangrez)"
  - "**GitHub**: [github.com/kashmir98](https://github.com/kashmir98)"
  - "**Location**: Fullerton, CA"
