title: "Musa Rangrez"
logo: "assets/headshot.png.jpg"
theme: "jekyll-theme-minimal"

# Uncomment the following if you need them:
# description: "Data Scientist Portfolio"
# show_downloads: true


# Technical Skills
technical_skills:
  - "Python"
  - "SQL"
  - "MATLAB"
  - "AWS"
  - "Tableau"

# Education
education:
  - degree: "B.S., Computer Science"
    institution: "Oregon State University at Corvallis"
    graduation: "Expected May 2025"
  - degree: "B.A., Public Health Policy"
    institution: "University of California, Irvine"
    graduation: "June 2022"

# Work Experience
work_experience:
  - title: "Data Analyst"
    company: "1800 Hiring"
    description: |
      - Analyzed recruitment data to improve candidate placement rate, optimizing the placement process and reducing time-to-fill by 15%.
      - Developed and distributed weekly performance reports for recruitment campaigns, increasing recruiter efficiency by 10%.
      - Cleaned and validated candidate data, improving data integrity and leading to a 20% enhancement in candidate-to-job matches.

# Projects
projects:
  - name: "NFL Big Data Bowl Competition 2025"
    link: "#"
  - name: "Chess Game"
    link: "#"
