title: "MUSA RANGREZ"
logo: "/assets/roundedheadshot.png"
theme: "jekyll-theme-minimal"
description: "I am passionate about working at the intersection of data, innovation, and strategy, constantly seeking to transform raw numbers into actionable insights. Here is a showcase of my skills and projects in data analysis, problem-solving, and innovative solutions. Explore how I use data to drive impact and create value."
# show_downloads: true


# Technical Skills
technical_skills:
  - "Python"
  - "SQL"
  - "MATLAB"
  - "AWS"
  - "Tableau"

# Education
education:
  - degree: "B.S., Computer Science"
    institution: "Oregon State University"
    graduation: "Expected May 2025"
  - degree: "B.A., Public Health Policy"
    institution: "University of California, Irvine"
    graduation: "June 2022"

# Work Experience
work_experience:
  - title: "Data Analyst Intern"
    company: "1800 Hiring"
    description: |
      - As a Data Analyst Intern at 1800 Hiring, I leveraged data-driven insights to enhance recruitment efficiency, achieving a 15% reduction in time-to-fill and a 20% improvement in candidate-to-job matches. I specialized in performance reporting, data cleaning, and process optimization to drive impactful recruitment outcomes.
# Projects
projects:
  - name: "NFL Big Data Bowl Competition 2025"
    link: "#"

