title: "  Musa Rangrez"
logo: "/assets/roundedheadshot.png"
theme: "jekyll-theme-minimal"

# Technical Skills
technical_skills:
  - "Python"
  - "SQL"
  - "MATLAB"
  - "AWS"
  - "Tableau"

# Education
education:
  - degree: "B.S., Computer Science"
    institution: "Oregon State University"
    graduation: "Expected May 2025"
  - degree: "B.A., Public Health Policy"
    institution: "University of California, Irvine"
    graduation: "June 2022"

# Work Experience
work_experience:
  - title: "Data Analyst Intern"
    company: "1800 Hiring"
    dates: "Jan 2023 – Jun 2024"
    description: >
      As a Data Analyst Intern at 1800 Hiring, I leveraged data-driven insights to enhance recruitment efficiency, achieving a 15% reduction in time-to-fill and a 20% improvement in candidate-to-job matches. I specialized in performance reporting, data cleaning, and process optimization to drive impactful recruitment outcomes.

  - title: "Undergraduate Research Assistant"
    company: "UCI Health"
    dates: "Jun 2021 – Mar 2022"
    description: >
      Conducted research on orthotropic appliance prototypes using MATLAB and machine learning to predict orthodontic corrections with 91.3% accuracy. Designed a Python/MATLAB interface to analyze clinical trial data, track algorithm performance, and optimize case planning for over 50 trials.


# Projects
projects:
  - name: "NFL Big Data Bowl Competition 2025"
    image: "/assets/reshot-football.png"
    link: "https://github.com/kashmir98/NFL-Big-Data-Bowl-2025"

# Contact Me
contact_me:
  email: "musarangrez@hotmail.com"
  linkedin: "https://linkedin.com/in/musarangrez"
  github: "https://github.com/kashmir98"
  location: "Fullerton, CA"  

